hw6/socialnetwork/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'socialnetwork.views.home', name='home'),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'socialnetwork/login.html'}),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^register$', 'socialnetwork.views.register', name='register'),

    url(r'^profile/(?P<id>\d+)$', 'socialnetwork.views.profile', name='profile'),
    url(r'^edit-profile$', 'socialnetwork.views.edit_profile', name='edit-profile'),
    url(r'^follower-stream$', 'socialnetwork.views.stream', name='follower-stream'),
    
    url(r'^add-post$', 'socialnetwork.views.add_post', name='add'),
    url(r'^delete-post$', 'socialnetwork.views.delete_post', name='delete'),
    url(r'^get-posts', 'socialnetwork.views.get_posts', name='get-posts'),
    url(r'^add-comment$', 'socialnetwork.views.add_comment', name='comment'),

    url(r'^follow/(?P<user_id>\d+)$', 'socialnetwork.views.follow', name='follow'),
     url(r'^image/(?P<id>\d+)$', 'socialnetwork.views.get_photo', name='image'),
)

hw6/webapps/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/$', include(admin.site.urls)),
    url(r'^socialnetwork/', include('socialnetwork.urls')),
    url(r'^$', RedirectView.as_view(url='/socialnetwork', permanent=False), name='index'),
)

hw6/socialnetwork/models.py
from django.db import models
from datetime import datetime
from django.db.models.signals import post_delete
from django.dispatch import receiver

# User class for built-in authentication module
from django.contrib.auth.models import User
    
class Comment(models.Model):
    comment = models.TextField(max_length=160, blank=False)
    user = models.ForeignKey(User)
    creation_date = models.DateTimeField(default=datetime.now, editable=False)
    
    def __unicode__(self):
        return self.comment
    
    class Meta:
        get_latest_by = 'creation_date'

class Post(models.Model):
    post_content = models.TextField(max_length=160)
    user = models.ForeignKey(User)
    creation_date = models.DateTimeField(default=datetime.now, editable=False)
    comments = models.ManyToManyField(Comment, related_name="comments+")
    
    def __unicode__(self):
        return self.post_content
    
    class Meta:
        get_latest_by = 'creation_date'
      
class UserInfo(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    age = models.IntegerField(blank=True, null=True)
    short_bio = models.TextField(max_length=430, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='uploads/')
    content_type = models.CharField(max_length=50)
    
@receiver(post_delete, sender=UserInfo)
def image_post_delete_handler(sender, **kwargs):
    UserInfo = kwargs['instance']
    storage, path = UserInfo.image.storage, UserInfo.image.path
    storage.delete(path)
    
class Followers(models.Model):
    follower = models.ForeignKey(User)
    following = models.ForeignKey(UserInfo)

hw6/socialnetwork/views.py
import re

from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.core import serializers
import json
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http.response import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string

from socialnetwork.forms import *
from socialnetwork.models import *


# from socialnetwork.forms import RegistrationForm, PostForm, EditForm
@login_required
def home(request):
    user = request.user
    following_users = get_followers(user)
    now = datetime.now()
    now.strftime('YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]')
    
    posts = Post.objects.all().order_by('-creation_date')
    
    return render(request, 'socialnetwork/home.html', {'posts' : posts, 'form' : PostForm(), 'following' : following_users, 'user' : user, 'timestamp' : str(now)})

@login_required
def profile(request, id):
    context = {}
    logged_in_user = request.user
    context['user'] = logged_in_user
    user = User.objects.get(id = id)
    context['editable'] = False;
    now = datetime.now()
    now.strftime('YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]')
    context['timestamp'] = str(now)

    if not user:
        posts = Post.objects.all().order_by('-creation_date')
        context['posts'] = posts
        return redirect(reverse('home'))

    userInfo = UserInfo.objects.get(user = user)

    context['profile_user'] = user
    following = Followers.objects.filter(follower = logged_in_user, following = userInfo)
    if following:
        context["following"] = True

    posts = Post.objects.filter(user = user).order_by('-creation_date')
    context['posts'] = posts

    if user.id is request.user.id:
        context['editable'] = True;

        editinfo_form = EditInfoForm(instance = userInfo)
        context['edit_form'] = editinfo_form

        user_form = EditUserForm(initial = {
                                'first_name': user.first_name,
                                'last_name': user.last_name,
                                'password1': user.password,
                                'password2': user.password,
                                })
        context['user_form'] = user_form
    return render(request, 'socialnetwork/profile.html', context)

@login_required
@transaction.atomic
def add_post(request):
    context = {}

    # Just display the registration form if this is a GET request.
    if request.method == 'GET':
        return redirect(reverse('home'))

    post_form = PostForm(request.POST)
    context['form'] = post_form

    # Validates the form.
    if not post_form.is_valid():
        return redirect(reverse('home'))

    # At this point, the form data is valid.  Register and login the user.
    new_post = Post(user = request.user, post_content = post_form.cleaned_data['post_content'])
    new_post.save()

    return redirect(reverse('home'))

@login_required
@transaction.atomic
def add_comment(request):
    context = {}

    if request.method == 'GET':
        return HttpResponse("Invalid request (GET)")

    post_id = request.POST['post_id']
    if not post_id:
        return HttpResponse("Invalid request: no reference to some post is given")
    
    comment = request.POST['comment']
    if not comment:
        return HttpResponse("Invalid request: no comment is given")
    
    post = Post.objects.get(id = post_id)
    if not post:
        return HttpResponse("Invalid request: you are trying to comment on a post that doen't exist")

    new_comment = Comment.objects.create(comment = comment, user=request.user)
    post.comments.add(new_comment)
    
    context['comments'] = [new_comment]
    context['post'] = post
    
    response_html = render_to_string('socialnetwork/comment_template.html', context)
    
    return HttpResponse(response_html, content_type = 'text/html')

@login_required
def get_posts(request):
    if request.method == 'GET':
        return Http404()
    
    context = {}
    timestamp = request.POST['timestamp']
    print timestamp
    
    if not timestamp:
        response_text = Post.objects.all().order_by('-creation_date')
    else:
        timestamp = datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S.%f')
        timestamp.strftime('YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]')
        
        posts = Post.objects.filter(creation_date__gt=timestamp).order_by('-creation_date')
        response_text = posts
    
    context['posts'] = response_text
    context['user'] = request.user
    now = datetime.now()
    now.strftime('YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]')
    
    following_users = get_followers(request.user)
    
    context['following'] = following_users
    
    response_html = render_to_string('socialnetwork/post_template.html', context)
    
    response = json.dumps({'timestamp': str(now),
               'html': str(response_html)})
    return HttpResponse(response, content_type = 'text/json')

def get_followers(user):
    following = Followers.objects.filter(follower = user)

    following_users = []
    for f in following:
        following_users.append(f.following)
    
    return following_users
    
@login_required
@transaction.atomic
def edit_profile(request):
    context = {}
    errors = []
    er_count = 0

    if request.method == 'GET':
        return redirect(reverse('profile', kwargs = {'id':request.user.id}))

    user_info = UserInfo()
    userinfo_form = EditInfoForm(request.POST, request.FILES, instance = user_info)
    user_form = EditUserForm(request.POST)

    # Validates the form.
    if (not userinfo_form.is_valid()) or (not user_form.is_valid()):
        try:
            userinfo_form.is_valid()
        except ValidationError, err:
            errors[er_count] = '; '.join(err.messages)
            er_count = er_count + 1

        try:
            user_form.is_valid()
        except ValidationError, err:
            errors[er_count] = '; '.join(err.messages)

        context['errors'] = errors
        context['edit_form'] = userinfo_form
        context['user_form'] = user_form
        context['user'] = request.user
        context['editable'] = True
        posts = Post.objects.filter(user = request.user).order_by('-creation_date')
        context['posts'] = posts
        now = datetime.now()
        now.strftime('YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]')
    
        context['timestamp'] = str(now)

        return render(request, 'socialnetwork/profile.html', context)


    user = User.objects.get(id = request.user.id)

    if user:
        if (user_form.cleaned_data['changed_password']):
            user.set_password(user_form.cleaned_data['password1'])

        user.first_name = user_form.cleaned_data['first_name']
        user.last_name = user_form.cleaned_data['last_name']
        user.save()

        old_user_info = UserInfo.objects.get(user = user)
        if old_user_info and old_user_info.image:
            old_user_info.delete()

        user_info.user = user
        if userinfo_form.cleaned_data['image']:
            user_info.content_type = userinfo_form.cleaned_data['image'].content_type
        user_info.save()


    return redirect(reverse('profile', kwargs = {'id':request.user.id}))

@login_required
def stream(request):
    posts = []

    user = request.user
    following_users = get_followers(user)

    for follow_user in following_users:
        f_user = follow_user.user
        user_posts = Post.objects.filter(user = f_user)
        posts.extend(user_posts)

    posts.sort(key = lambda post: post.creation_date, reverse = True)
    
    now = datetime.now()
    now.strftime('YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]')
    return render(request, 'socialnetwork/stream.html', {'posts' : posts, 'user' : user, 'following' : following_users, 'timestamp' : str(now)})

@login_required
@transaction.atomic
def follow(request, user_id):
    context = {}

    if 'follow' not in request.GET:
        return redirect(reverse('home'))

    action = request.GET['follow'];
    follower_id = request.user.id
    following_id = user_id

    user_follower = User.objects.get(id = follower_id)
    user_following = User.objects.get(id = following_id)

    if (not user_follower) or (not user_following):
        context['errors'] = 'Please select an existing user'
        context['posts'] = Post.objects.all().order_by('-creation_date')
        context['form'] = PostForm()

        following_users = get_followers(request.user)
        context['following'] = following_users
        return render(request, 'socialnetwork/home.html', context)

    userinfo_following = UserInfo.objects.get(user = user_following)

    following_exists = Followers.objects.filter(follower = user_follower, following = userinfo_following)
    if (action == u'follow') and (not following_exists):
        new_following = Followers(follower = user_follower, following = userinfo_following)
        new_following.save()
    elif (action == u'unfollow') and (following_exists):
        following_exists.delete()

    return HttpResponse();

@login_required
@transaction.atomic
def delete_post(request):
    errors = []
    kwargs = {}

    referer = get_referer_view(request, None)
    if 'stream' in referer:
        url = 'follower-stream'
        kwargs = {'id':request.user.id}
    elif 'profile' in referer:
        url = 'profile'
        kwargs = {'id':request.user.id}
    else:
        url = 'home'

    if request.method == 'GET':
        return redirect(reverse(url, kwargs = kwargs))

    post_id = request.POST['post_id']

    if not post_id:
        return redirect(reverse(url, kwargs = kwargs))

    try:
        post_to_delete = Post.objects.get(id = post_id, user = request.user)
        post_to_delete.delete()
    except get_object_or_404:
        errors.append('This post either does not exist or is owned by another user.')

hw6/socialnetwork/templates/socialnetwork/base.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'socialnetwork/css/main.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'socialnetwork/css/grid.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'socialnetwork/css/forms.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'socialnetwork/css/posts.css' %}" type="text/css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script type='text/javascript' src="{% static 'socialnetwork/js/socialnetwork.js' %}"></script>
	<title>{% block title %} SoNet - Social Network {% endblock %}</title>
</head>

<body>
	<div class="header">{% block header %} {% endblock %}</div>
	<div align="center" class="body"><div class="heading-wrapper">{% block heading %} {% endblock %}</div></div>
	
	{% for error in errors %}
	<div align="center" class="error-wrapper">
		<span class="error">{{ error }}</span>
	</div>
	{% endfor %}
	
	<div class="content">{% block content %} {% endblock %}</div>
	<div class="footer">{% block footer %} {% endblock %}</div>
</body>
</html>

hw6/socialnetwork/templates/socialnetwork/comment_template.html
 {% load static %}
 {% for comment in comments %}
<div class="wrapper">
	<div class="comment-wrapper top">
		{% if comment.user.userinfo.image %} 
			<img class="icon comment-user round inline" src="{% url 'image' comment.user.id %}" alt="{{comment.user.username}}"> 
		{% else %} 
			<img class="icon comment-user round inline" src="{% static 'socialnetwork/images/user.png' %}" alt="{{comment.user.username}}"> 
		{% endif %} 
		<div class="comment-content">
			<a class="comment-user link" href="{% url 'profile' comment.user.id %}">{{comment.user.username}} : </a>
			<span>{{comment}}</span>
		</div>
	</div>
	<div class="comment-wrapper bottom">
		<span class="post-date">{{comment.creation_date}}</span>
	</div>
</div>
{% endfor %}

hw6/socialnetwork/templates/socialnetwork/header.html
{% extends "socialnetwork/base.html" %}
{% load static %}
{% block header %}
<div class="logo inline">
	<a href="/socialnetwork/" class="sonet">SoNet</a>
</div>
<div class="navbar fright">
	<div class="navtab">
		<a class="link" href="{% url 'home' %}">
			<img class="icon" src="{% static 'socialnetwork/images/home.png' %}">
			<span class="nav"> Home</span>
		</a>
	</div>
	{% if user.id %}
	<div class="separator"></div>
	<div class="navtab">
		<a class="link" href="{% url 'follower-stream' %}">
			<img class="round icon" src="{% static 'socialnetwork/images/stream.png' %}">
			<span class="nav"> Followers Stream</span>
		</a>
	</div>
	<div class="separator"></div>
	<div class="navtab">
		<a class="link" href="{% url 'profile' user.id %}">
			<img class="icon" src="{% static 'socialnetwork/images/user_post.png' %}">
			<span class="nav"> Profile</span>
		</a>
	</div>
	<div class="separator"></div>
	<div class="navtab last">
		<a class="link" href="{% url 'logout' %}">
			<img class="logout icon" src="{% static 'socialnetwork/images/logout.png' %}">
			<span class="nav"> Logout</span>
		</a>
	</div>
	<span class="user block">{{user.username}}</span>
	{% endif %}
</div>
{% endblock %}

hw6/socialnetwork/templates/socialnetwork/home.html
{% extends "socialnetwork/header.html" %} 
{% load static %}
{% block heading %}
	<h3 class="calligraphy small">Posts Feed</h3>
{% endblock %}

{% block content %}
<div class="new-post">
	<form action="{% url 'add' %}" method="post">
		<div class="add-post-form">
			<table>{{form}}
			</table>
			{% csrf_token %}
			<input disabled maxlength="3" size="1" value="160" id="counter" class="counter inline">
			<input class="submit inline postit" type="submit" value="">
		</div>
	</form>
</div>
<div class="centered">
	{% include "socialnetwork/posts.html" with posts=posts following=following user=user %}
</div>

<script>
	$(function() {

		$("#id_post_content").keyup(function() {

			textCounter($(this), 'counter', 160);
			return false;
		});
	});

	function textCounter(element, field2, maxlimit) {

		var countfield = document.getElementById(field2);
		var value = $(element).val();
		if (value.length > maxlimit) {
			$(element).val(value.substring(0, maxlimit));
			countfield.style.color = "red";
			return false;
		}
		else {
			countfield.value = maxlimit - $(element).val().length;
		}
	}
</script>
{% endblock %}


hw6/socialnetwork/templates/socialnetwork/login.html
{% extends "socialnetwork/header.html" %} 

{% block heading %}
<h3 class="calligraphy">Welcome!</h3>
<span class="heading">Please sign in below</span>
{% endblock %}

{% block content %}
<div class="login">
	<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
		<div class="form">
			<table>
				{{ form }}
			</table>
			<div align="center">
				<span class="label inline">Not already a user? </span>
				<a class="register link" href="/socialnetwork/register">Register</a>
			</div>
			<input class="submit" type="submit" value="Login" />
			<input type="hidden" name="next" value="{{ next }}" />
		</div>

		{% csrf_token %}
	</form>
</div>
{% endblock %}

hw6/socialnetwork/templates/socialnetwork/post_template.html
 {% load static %}
 {% for post in posts %}
<div class="wrapper" id="post_{{post.id}}">
	<div class="post-wrapper top">
		{% if post.user.userinfo.image %} 
			<img class="icon post-user round inline" src="{% url 'image' post.user.id %}" alt="{{post.user.username}}"> 
		{% else %} 
			<img class="icon post-user round inline" src="{% static 'socialnetwork/images/user.png' %}" alt="{{post.user.username}}"> 
		{% endif %} 
		<a class="post-user link" href="{% url 'profile' post.user.id %}">{{post.user.username}}</a>
		{% if post.user == user %}
		<form class="delete fright" action="{% url 'delete' %}" method="post">
			<input type="hidden" name="post_id" value="{{ post.id }}">
			<button class="empty" type="submit" name="submit" value=" ">
				<img src="{% static 'socialnetwork/images/post_delete.png' %}">
			</button>
			{% csrf_token %}
		</form>
		{% endif %}
		<div class="post-content">
			<span>{{post}}</span>
		</div>
	</div>
	<div class="post-wrapper bottom">
		{% if post.user != user %} 
			{% if post.user.userinfo in following %} 
				<a class="link following fleft" onclick="return toggleFollow(this);" href="{% url 'follow' post.user.id %}">Following</a> 
			{% else %} 
				<a class="link following fleft" onclick="return toggleFollow(this);" href="{% url 'follow' post.user.id %}">Follow Me!</a> 
			{% endif %} 
		{% endif %}
		<span class="post-date">{{post.creation_date}}</span>
	</div>
	<div class="comments-wrapper" id="comments-wrapper">
		{% if post.comments.all %}
			{% include "socialnetwork/comment_template.html" with post=post comments=post.comments.all %}
		{% endif %}
	</div>
	<div class="new-comment-wrapper">
		<div class="new-comment">
			{% if user.userinfo.image %} 
				<img class="icon round inline" src="{% url 'image' user.id %}" alt="{{user.username}}"> 
			{% else %} 
				<img class="icon round inline" src="{% static 'socialnetwork/images/user.png' %}" alt="{{user.username}}"> 
			{% endif %} 
			<form action="{% url 'comment' %}" method="post" class="comment-form" id="add-comment-{{post.id}}">
				<textarea name="comment" rows="1" cols="80" ></textarea>
				<input type="hidden" name="post_id" value="{{ post.id }}">
				{% csrf_token %}
			</form>
			<a class="submit inline comment" onclick="return add_comment('{{post.id}}');"></a>
		</div>
	</div>
</div>
{% endfor %}

<script>
	$(function() {
	});

	function add_comment(id) {
		$("#add-comment-" + id).submit(function(e) {
			    e.preventDefault();
			    var form = $(this);
			    var postData = $(this).serializeArray();
			    var formURL = $(this).attr("action");
			    $.ajax({
			        url : formURL,
			        type: "POST",
			        data : postData,
			        success:function(data, textStatus, jqXHR) {
			        	var post = $('#post_' + id)
			        	var comments_wrapper = $(post).find("#comments-wrapper")
			            var last_comment = $(comments_wrapper).last();
			            if (last_comment.length == 0) {
			            	$(comments_wrapper).prepend(data);
			            	var text = $(form).find('textarea');
			            	$(text).val('');
			            	return;
			            }
			            
			            $(last_comment).append(data);
			            var text = $(form).find('textarea');
		            	$(text).val('');
			        },
			        error: function(jqXHR, textStatus, errorThrown) {
			        }
			    });
			});
				 
		$("#add-comment-" + id).submit();
				
		return false;
	}

</script>

hw6/socialnetwork/templates/socialnetwork/posts.html
{% load static %}
<div id="posts-wrapper" class="posts column">
<input type="hidden" id="timestamp" value="{{ timestamp }}">
	<div id="token">{% csrf_token %}</div>
	<div id="posts-list" class="history">
		{% if not posts %}
		<div align="center">
			<span>No posts</span>
		</div>
		{% endif %}
		{% include "socialnetwork/post_template.html" with posts=posts following=following user=user %}
	</div>
</div>

<script>
	$(function() {
		window.setInterval(sendRequest, 20000);
	});
	
	function sendRequest() {
	    var time = $("#timestamp").val();
	    var token = $("#token > input").val();
	    var req = $.post( "get-posts", { timestamp: time, csrfmiddlewaretoken: token }, function( data ) {
		    		$("#timestamp").val(data.timestamp);
		    		handleResponse(data.html);
		    	}, "json");
	    return false;
	}

	function handleResponse(data) {
		
		var wrapper = $("#posts-list")
		$(wrapper).prepend(data);
		
	}

	function toggleFollow(element) {
		var text = $(element).text();
		var href = $(element).attr('href');
		var params;
		if (text == "Follow Me!") {
			params = '?follow=follow';
			text = "Following";
		} else if (text == "Following") {
			params = '?follow=unfollow';
			text = "Follow Me!";
		}
		
		$.get(href + params, function(data) {
			$(element).text(text);
		});
		
		return false;
	}
</script>

hw6/socialnetwork/templates/socialnetwork/profile.html
{% extends "socialnetwork/header.html" %}
{% load static %}
{% block heading %}
	<h3 class="calligraphy small">Profile</h3>
{% endblock %}

{% block content %}
<div class="info column">
	{% if user.userinfo.image %} 
		<img class="w100 round" src="{% url 'image' user.id %}" alt="{{user.username}}"> 
	{% else %} 
		<img class="w100 round"
			src="{% static 'socialnetwork/images/user.png' %}" alt="User"> 
	{% endif %}
	{% if editable %}
		<a class="edit action fright" onclick="return toggleEdit(false);">
			<img class="icon" src="{% static 'socialnetwork/images/edit.png' %}">
		</a>
		<a id="cancel" class="cancel action fright" onclick="return toggleEdit(true);">
			<img class="icon" src="{% static 'socialnetwork/images/cancel.png' %}">
		</a>
		<a id="submit" class="action fright" onclick="return submit();">
			<img class="icon" src="{% static 'socialnetwork/images/submit.png' %}">
		</a>
		<div class="row">
			<label>Username:</label>
			<span>{{user.username}}</span>
		</div>
		<form id="user-edit" action="{% url 'edit-profile' %}" method="post" enctype="multipart/form-data">
			<table>{{user_form}}{{edit_form}}
			</table>
			{% csrf_token %}
		</form>
	{% else %}
		{% if following %}
			<a class="link follow fright" onclick="return toggleFollow(this);" href="{% url 'follow' profile_user.id %}">Following</a>
		{% else %}
			<a class="link follow fright" onclick="return toggleFollow(this);" href="{% url 'follow' profile_user.id %}">Follow Me!</a>
		{% endif %}
		<div class="row">
			<label>First name:</label>
			<span>{{user.first_name}}</span>
		</div>
		<div class="row">
			<label>Last name:</label>
			<span>{{user.last_name}}</span>
		</div>
		<div class="row">
			<label>Age:</label>
			<span>{{userinfo.age}}</span>
		</div>
		<div class="row">
			<label>Username:</label>
			<span>{{user.username}}</span>
		</div>
		<div class="row">
			<label>Short bio:</label>
			<span>{{userinfo.short_bio}}</span>
		</div>
	{% endif %}
</div>
{% include "socialnetwork/posts.html" with posts=posts following=following user=user %}

<script>
	$(function() {

		toggleEdit(true);

		$('#id_short_bio').prop('cols', 20);
		$('#id_short_bio').width(190);
	});

	function toggleEdit(flag) {

		var elements = $("form#user-edit :input");
		elements.each(function(index, el) {

			$(el).prop('disabled', flag);
		});

		var label = $('label[for="id_password2"]');
		label.parent().parent().prop('hidden', flag);
		label = $('label[for="id_password1"]');
		label.parent().parent().prop('hidden', flag);

		if (!flag) {
			$('#submit').removeClass('hidden');
			$('#cancel').removeClass('hidden');
		}
		else {
			$('#submit').addClass('hidden');
			$('#cancel').addClass('hidden');
		}

		return false;
	}

	function submit() {
		document.getElementById("user-edit").submit();
		return false;
	}
</script>
{% endblock %}

hw6/socialnetwork/templates/socialnetwork/register.html
{% extends "socialnetwork/header.html" %} 

{% block heading %}
<h3 class="calligraphy">Welcome!</h3>
<span class="heading">Please sign up below</span>
{% endblock %}

{% block content %}
<div class="register">
	<form method="post" action="{% url 'register' %}" enctype="multipart/form-data">
		<table>{{form}}{{userinfo_form}}
		</table>
		{% csrf_token %}
		<input class="submit" type="submit" value="Register" />
	</form>
</div>
{% endblock %}

hw6/socialnetwork/templates/socialnetwork/stream.html
{% extends "socialnetwork/header.html" %} 
{% load static %}
{% block heading %}
	<h3 class="calligraphy small">Followers Feed</h3>
{% endblock %}

{% block content %}
<div class="centered">
	{% include "socialnetwork/posts.html" with posts=posts following=following user=user %}
</div>

{% endblock %}